.PHONY: clean All

All:
	@echo "----------Building project:[ SAL - Debug ]----------"
	@cd "C:\Users\surafel911\Documents\Coding\Projects\Libraries\SAL\SAL" && "$(MAKE)" -f  "SAL.mk"
clean:
	@echo "----------Cleaning project:[ SAL - Debug ]----------"
	@cd "C:\Users\surafel911\Documents\Coding\Projects\Libraries\SAL\SAL" && "$(MAKE)" -f  "SAL.mk" clean
